USE master
GO

CREATE DATABASE PR_SalesManager
GO
USE PR_SalesManager
GO
CREATE TABLE Staff
(
	IDStaff INT IDENTITY PRIMARY KEY,
	Account NVARCHAR(50) NOT NULL,
	Password NVARCHAR(50) NOT NULL,
	FullName NVARCHAR(50) NOT NULL,
	Sex BIT NOT NULL, -- True: Nam, False: Nữ
	PhoneNumber NVARCHAR(50) NOT NULL,
	DateOfBirth DATE NOT NULL,
	Address NVARCHAR(50) NOT NULL,
	Gmail NVARCHAR(50) NOT NULL DEFAULT N'Chưa Cập Nhật',
	Type INT NOT NULL DEFAULT 0, -- 1 : Quản Lý, 0 : Nhân Viên
)
GO
CREATE TABLE Customer
(
	IDCustomer INT IDENTITY PRIMARY KEY,
	FullName NVARCHAR(50) NOT NULL,
	PhoneNumber NVARCHAR(50) NOT NULL,
	Gmail NVARCHAR(50) NOT NULL DEFAULT N'Chưa Cập Nhật',
	Address NVARCHAR(50) NOT NULL,
)
GO
CREATE TABLE ProductType
(
	IDType INT IDENTITY PRIMARY KEY,
	NameType NVARCHAR(50) NOT NULL
)
GO
CREATE TABLE Product
(
	IDProduct INT IDENTITY PRIMARY KEY,
	NameProduct NVARCHAR(50) NOT NULL,
	Amount INT NOT NULL,
	Price FLOAT NOT NULL,
	Pic IMAGE NOT NULL,
	Describe NTEXT NOT NULL DEFAULT N'Chưa Cập Nhật',
	IDType INT NOT NULL FOREIGN KEY REFERENCES dbo.ProductType(IDType)
)
GO
CREATE TABLE Bill
(
	IDBill INT IDENTITY PRIMARY KEY,
	IDStaff INT FOREIGN KEY REFERENCES dbo.Staff(IDStaff),
	IDCustomer INT NOT NULL FOREIGN KEY REFERENCES dbo.Customer(IDCustomer),
	DatePay DATE DEFAULT SYSDATETIME() NOT NULL,
	TotalPrice FLOAT NOT NULL
)
GO

CREATE TABLE BillDetails
(
	IDBillDetails INT IDENTITY PRIMARY KEY,
	IDProduct INT NOT NULL FOREIGN KEY REFERENCES dbo.Product(IDProduct),
	IDBill INT NOT NULL FOREIGN KEY REFERENCES dbo.Bill(IDBill),
	Price FLOAT NOT NULL,
	Amount INT NOT NULL
)